version: '3'
services:
  postgresql:
    container_name: postgres_container
    build: ./
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
    restart: always

volumes:
  database-data:
